### ISSUE TITLE
contact | MiaoTony's小窝

### ISSUE THREAD

**Issue by miaotony** [miaotony/miaotony.github.io#4]
https://miaotony.github.io/contact/ 

 contact | MiaoTony's小窝

**Comment by miaotony** [comment]
嘻嘻嘻~  
欢迎各位大佬的来访呀~  
**来给我留个言呗~**

**Comment by Yohoa** [comment]
（大佬我来了


__Mark__ 一下！！

**Comment by miaotony** [comment]
@Yohoa 噫，欢迎喵~

**Comment by lemon-netizen** [comment]
666666666爱你哦

**Comment by zbw0520** [comment]
膜 大佬 **：）**

**Comment by Flexiston** [comment]
喜欢你的文章风格~

**Comment by miaotony** [comment]
> @Flexiston
> 喜欢你的文章风格~

好耶~   
大佬可以来交换友链呢（

**Comment by Flexiston** [comment]
> @miaotony
> > @Flexiston
> > 喜欢你的文章风格~
> 
> 好耶~   
> 大佬可以来交换友链呢（

好呢~
名称：Flexiston
网址：https://www.flexiston.com
头像：https://cdn.jsdelivr.net/gh/Flexiston/CDN/img/avatar.png
简介：立即行动吧，未来要自己争取

**Comment by userid** [comment]
blog的页面太华丽了。加载有点满。。

**Comment by DWCTSHAO** [comment]
膜拜大佬

**Comment by miaotony** [comment]
> @Flexiston
> > @miaotony
> > > @Flexiston
> > > 喜欢你的文章风格~
> > 
> > 好耶~   
> > 大佬可以来交换友链呢（
> 
> 好呢~
> 名称：Flexiston
> 网址：https://www.flexiston.com
> 头像：https://cdn.jsdelivr.net/gh/Flexiston/CDN/img/avatar.png
> 简介：立即行动吧，未来要自己争取

hi~ 大佬您博客的证书过期了唉，记得 renew 一下喵~

**Comment by Sofar1994** [comment]
代码块怎么改底色啊，而且我看你的代码块右上角识别出python，我的就是none,这可怎么办啊。

**Comment by miaotony** [comment]
> @Sofar1994
> 代码块怎么改底色啊，而且我看你的代码块右上角识别出python，我的就是none,这可怎么办啊。

代码块配色方案在主题配置里可以改，代码块要标出语言才能自动高亮，需要在 markdown 里指明所用的编程语言，比如 python 的话就是

```python 
# 假如这里是代码块
    ```python
    balabala 

```

**Comment by lingyi888** [comment]
红帽杯colorful code最后那个脚本跑不起来

Traceback (most recent call last):
  File "C:\Users\OK\Desktop\Python学习\ctf\1.py", line 32, in <module>
    color = colors[int(l[cnt])]
NameError: name 'l' is not defined

大佬给解答一下呗

**Comment by miaotony** [comment]
> @lingyi888
> 红帽杯colorful code最后那个脚本跑不起来
> 
> Traceback (most recent call last):
>   File "C:\Users\OK\Desktop\Python学习\ctf\1.py", line 32, in <module>
>     color = colors[int(l[cnt])]
> NameError: name 'l' is not defined
> 
> 大佬给解答一下呗

看了一下，这个 `l` 是 `data1` 里的数据，文章里的代码也顺便更新了一下，不好意思贴上来的时候没注意漏掉了。

您可以直接在 [对应博客](https://miaotony.xyz/2021/05/24/CTF_2021RedHat/) 下面评论哈（

**Comment by rantrism** [comment]
您好～我是腾讯云+社区的运营，关注了您分享的技术文章，觉得内容很棒，我们诚挚邀请您加入腾讯云自媒体分享计划。完整福利和申请地址请见：https://cloud.tencent.com/developer/support-plan
作者申请此计划后将作者的文章进行搬迁同步到社区的专栏下，你只需要简单填写一下表单申请即可，我们会给作者提供包括流量、云服务器等，另外还有些周边礼物。  
我们诚挚的邀请您并期待您的加入~

**Comment by miaotony** [comment]
> @9bie
> 喵喵新年快乐呀！

鳖鳖新年快乐，虎年大吉呀！

**Comment by m4xlmum** [comment]
tql

**Comment by hmsjy2017** [comment]
求大佬教我接入 DNS42 网络（
